name: pr

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |-
          curl -X POST https://api.github.com/repos/ezaki/test/pulls \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -d "{\"title\": \"Amazing new feature\", \"body\": \"Please pull this in!\", \"head\": \"master\", \"base\": \"develop\"}"
